//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Totira.Bussiness.UserService.EmailTemplates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailTemplateResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplateResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Totira.Bussiness.UserService.EmailTemplates.EmailTemplateResource", typeof(EmailTemplateResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;&lt;meta charset=&quot;UTF-8&quot;&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://fonts.googleapis.com&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://fonts.gstatic.com&quot; crossorigin&gt;&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&amp;family=Lato:wght@400;700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;&lt;title&gt;mail&lt;/title&gt;&lt;style&gt;body{font-family:sans-serif}.fredoka-font{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApprovedPropertyOwnership {
            get {
                return ResourceManager.GetString("ApprovedPropertyOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;&lt;meta charset=&quot;UTF-8&quot;&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://fonts.googleapis.com&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://fonts.gstatic.com&quot; crossorigin&gt;&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&amp;family=Lato:wght@400;700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;&lt;title&gt;mail&lt;/title&gt;&lt;style&gt;.fredoka-font{font-family:sans-serif}.cent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroupApplicationProfileSharingTemplate {
            get {
                return ResourceManager.GetString("GroupApplicationProfileSharingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html&gt;&lt;head&gt;&lt;meta charset=&quot;UTF-8&quot;&gt;&lt;title&gt;&lt;/title&gt;&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Lato&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;&lt;style&gt;body{font-family:Lato,sans-serif;margin:0}.btn{background:#0c6dff;border-radius:100px;color:#fff;width:191px;height:40px;border:none}&lt;/style&gt;&lt;/head&gt;&lt;body&gt;&lt;table width=&quot;100%&quot; style=&quot;background-color:#0e2c6c&quot;&gt;&lt;tr&gt;&lt;td align=&quot;left&quot; style=&quot;padding:32px 0 32px 64px&quot;&gt;&lt;img src=&quot;https://bucket-totira-publicresources-development.s3.amazonaws.com/icons/logoIcon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InviteCoApplicantTemplate {
            get {
                return ResourceManager.GetString("InviteCoApplicantTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html lang=&quot;en&quot;&gt;&lt;head&gt;&lt;meta charset=&quot;UTF-8&quot;&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://fonts.googleapis.com&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://fonts.gstatic.com&quot; crossorigin&gt;&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&amp;family=Lato:wght@400;700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;&lt;title&gt;mail&lt;/title&gt;&lt;style&gt;body{font-family:sans-serif}.fredoka-font{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProfileSharingTemplate {
            get {
                return ResourceManager.GetString("ProfileSharingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot;&gt; &lt;head&gt; &lt;link rel=&quot;preconnect&quot; href=&quot;https://fonts.googleapis.com&quot;/&gt; &lt;link rel=&quot;preconnect&quot; href=&quot;https://fonts.gstatic.com&quot; crossorigin/&gt; &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Fredoka&amp;family=Lato&amp;display=swap&quot; rel=&quot;stylesheet&quot;/&gt; &lt;style type=&quot;text/css&quot;&gt; body{font-family: Lato, sans-serif; color: #000;}&lt;/style&gt; &lt;/head&gt; &lt;body style=&quot;font-size: 20px; background: #f5f5f5;&quot;&gt; &lt;div style=&quot;margin-top: 1%; margin-right: 10%; margin-left: 10%; padding-top: 5%;&quot;&gt; &lt;div style=&quot;background:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReferralAcquaintanceTemplate {
            get {
                return ResourceManager.GetString("ReferralAcquaintanceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot;&gt; &lt;head&gt;&lt;/head&gt;&lt;style type=&quot;text/css&quot;&gt; body{font-family: Lato, sans-serif; color: #000;}&lt;/style&gt; &lt;body style=&quot;font-size: 20px; background: #f5f5f5;&quot;&gt; &lt;div style=&quot;margin-top: 1%; margin-right: 10%; margin-left: 10%; padding-top: 5%;&quot;&gt; &lt;div style=&quot;background: #fff; padding: 10px;&quot;&gt; &lt;div&gt; &lt;div&gt; &lt;div style=&quot;margin-bottom: 40px; padding-top: 32px; text-align: center;&quot;&gt; &lt;h4&gt;&lt;img src=&quot;https://bucket-totira-publicresources-development.s3.amazonaws.com/totiraIcon.png&quot; alt=&quot;Logo&quot; loading=&quot;eager&quot;/&gt;&lt;/h4&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReferralLandlordTemplate {
            get {
                return ResourceManager.GetString("ReferralLandlordTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html lang=&quot;en&quot;&gt;&lt;head&gt; &lt;meta charset=&quot;UTF-8&quot;&gt; &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt; &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt; &lt;link rel=&quot;preconnect&quot; href=&quot;https://fonts.googleapis.com&quot;&gt; &lt;link rel=&quot;preconnect&quot; href=&quot;https://fonts.gstatic.com&quot; crossorigin&gt; &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&amp;family=Lato:wght@400;700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt; &lt;title&gt;mail&lt;/title&gt; &lt;style&gt;body{font-family: sans-serif}.fred [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RejectedPropertyOwnership {
            get {
                return ResourceManager.GetString("RejectedPropertyOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot;&gt;&lt;head&gt;&lt;meta charset=&quot;UTF-8&quot;&gt;&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;&lt;title&gt;mail&lt;/title&gt;&lt;style&gt;body,html{height:100%;margin:0;display:flex;align-items:center;justify-content:center;font-family:Arial}.centered-text{text-align:center}p.name{color:#0e2c6c;font-size:28px}.pb-48{padding-bottom:48px}.mt-15{margin-top:15px}.code{color:#0c6dff}.centered-text div{font-size:20px;color:#28293d;padding-bottom:16px}.btn{backgr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VerifiedProfile {
            get {
                return ResourceManager.GetString("VerifiedProfile", resourceCulture);
            }
        }
    }
}
